name: CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick, gd
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
